### ISSUE TITLE
1.0.6 - Ate craved food, craving not satisfied

### ISSUE THREAD

**Issue by st753m** [Darkhax-Minecraft/Cravings#11]
I'm playing with a custom collection of mods including Cravings.  An early craving was harvestcraft's Kiwi Smoothie, which I managed to eat shortly after the craving began.  It didn't register.  There was no notification in chat, nor did I get the buff.  A few minutes later, I got the debuffs from "failing to satisfy my craving for kiwi smoothie" even though I'd eaten 2 by that point.

Other mods in my set that might be interfering?
 - Harvestcraft
 - AppleSkin
 - Hunger Overhaul
 - Nutrition
 - Rustic (the Olive Oil system is disabled in its config)
 - The Betweenlands (which I wasn't in)
 - Tough as Nails

Edit: The cravings for Eggnog and Blueberry juice also failed, while other items from Harvestcraft have been a success.  The common trait between all of them is that they were added to my Tough As Nails config as drinks.

Edit 2: Renaming this issue after getting more confirming data:  I just got 2 more cravings failed despite drinking them (HC's cola soda and strawberry milkshake) while non-drink foods continue to work.  Something with how Tough as Nails alters foods to also cure thirst is interfering with the cravings system.

**Comment by Darkhax** [comment]
Sorry for not responding sooner, I didn't see your edits. You are right that this is an issue introduced by Tough as Nails and their system for handling food. I have added some code to my system for tracking things that should fix this issue and allow both mods to work together.

**Comment by Swordstone86** [comment]
This is still an issue in the mod as of mod version 1.0.11. Had a craving for Plum Juice, drank it, but craving was not satisfied due to it being registered in the TAN config as a drink.
